# Generated by Django 4.0.2 on 2022-02-12 13:19

from django.db import migrations, models
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=19)),
            ],
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
        ),
    ]
