# Generated by Django 4.0.2 on 2022-02-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_options_alter_city_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
